INSERT INTO QuestGiver (quest_giver_name, sex, race, faction) VALUES
	('Mama Murphy', 'Female', 'Human', 'Commonwealth Minutemen'),
	('Ellie Perkins', 'Female', 'Human', 'Valentine Detective Agency'),
	('Nick Valentine', 'Male', 'Synth', 'Valentine Dective Agency'),
	('Doctor Amari', 'Female', 'Human', 'Goodneighbor'),
	('Brian Virgil', 'Male', 'Super Mutant', 'Independdent'),
	('Shaun/Father', 'Male', 'Human', 'The Institute'),
	('Preston Garvey', 'Male', 'Human', 'Commonwealth Minutemen'),
	('Sturges', 'Male', 'Human', 'Commonwealth Minutemen'),
	('Blake Abernathy', 'Male', 'Human', 'Independent'),
	('Abraham Finch', 'Male', 'Human', 'Independent'),
	('Jake Finch', 'Male', 'Human', 'Independent'),
	('Supervisor White', 'Female', 'Mr Handy', 'Graygarden'),
	('Local Settler', 'Random', 'Random', 'Random'),
	('Radio Freedom', 'N/A', 'N/A', 'Commonwealth Minutemen'),
	('Pip-Boy', 'N/A', 'N/A', 'Commonwealth Minutemen'),
	('Military Frequency AF95', 'N/A', 'N/A', 'Brotherhood of Steel'),
	('Paladin Danse', 'Male', 'Synth', 'Brotherhood of Steel'),
	('Elder Maxson', 'Male', 'Human', 'Brotherhood of Steel'),
	('Proctor Ingram', 'Female', 'Human', 'Brotherhood of Steel'),
	('Lancer Captain Kells', 'Male', 'Human', 'Brotherhood of Steel'),
	('Knight Rhys', 'Male', 'Human', 'Brotherhood of Steel'),
	('Proctor Teagan', 'Male', 'Human', 'Brotherhood of Steel'),
	('Proctor Quinlan', 'Male', 'Human', 'Brotherhood of Steel'),
	('Scribe Haylen', 'Female', 'Human', 'Brotherhood of Steel'),
	('Senior Scribe Neriah', 'Female', 'Human', 'Brotherhood of Steel'),
	('Desdemona', 'Female', 'Human', 'The Railroad'),
	('P.A.M.', 'Female', 'Assaultron', 'The Railroad'),
	('Stanley Carrington', 'Male', 'Human', 'The Railroad'),
	('Drummer Boy', 'Male', 'Human', 'The Railroad'),
	('Caretaker', 'Male', 'Human', 'The Railroad'),
	('Tinker Tom', 'Male', 'Human', 'The Railroad'),
	('Newton Oberly', 'Male', 'Human', 'The Institute'),
	('Isaac Karlin', 'Male', 'Human', 'The Institute'),
	('Justin Ayo', 'Male', 'Human', 'The Institute'),
	('Evan Watson', 'Male', 'Human', 'The Institute'),
	('Clayton Holdren', 'Male', 'Human', 'The Institute'),
	('Alan Binet', 'Male', 'Human', 'The Institute'),
	('Alana Secord', 'Female', 'Human', 'The Institute'), 
	('Molly', 'Female', 'Miss Handy', 'Independent'),
	('Vadim Bobrov', 'Male', 'Human', 'Diamond City'),
	('Trinity Tower Radio', 'N/A', 'N/A', 'Independent'),
	('Tina De Luca', 'Female', 'Human', 'Vault 81'),
	('Paul Pembroke', 'Male', 'Human', 'Colonial Taphouse'),
	('Edward Deegan', 'Male', 'Ghoul', 'Cabot House'),
	('Erin Combes', 'Female', 'Human', 'Vault 81'),
	('Donny Kowalski', 'Male', 'Human', 'Independent'),
	('Priscilla Penske', 'Female', 'Human', 'Vault 81'),
	('Honest Dan', 'Male', 'Human', 'Old Man Stockton'),
	('Danny Sullivan', 'Male', 'Human', 'Diamond City Security'),
	('Billy', 'Male', 'Human', 'Independent'),
	('Ironsides', 'Male', 'Sentry Bot', 'USS Constitution'),
	('Theodore Collins', 'Male', 'Human', 'Independent'),
	('Wolfgang', 'Male', 'Human', 'Raiders'),
	('Trudy', 'Female', 'Human', 'Independent'),
	('Moe Cronin', 'Male', 'Human', 'Diamond City'),
	('Abbot', 'Male', 'Human', 'Diamond City'),
	('Pickman', 'Male', 'Human', 'Independent'),
	('Daisy', 'Female', 'Ghoul', 'Goodneighbor'),
	('Sully Mathis', 'Male', 'Human', 'Raider'),
	('Katy Pinn', 'Female', 'Human', 'Vault 81'),
	('Piper Wright', 'Female', 'Human', 'Publick Occurrences'),
	('Bobbi No-Nose', 'Female', 'Ghoul', 'Goodneighbor'),
	('Private Harts Holotape', 'N/A', 'N/A', 'Independent'),
	('Marty Bullfinchs Holotape', 'N/A', 'N/A', 'Independent'),
	('Darcy Pembroke', 'Female', 'Human', 'Diamond City'),
	('Irma', 'Female', 'Human', 'Goodneighbor'),
	('Jack Cabot', 'Male', 'Human', 'Cabot House'),
	('Kent Connolly', 'Male', 'Ghoul', 'Goodneighbor'),
	('Rufus Rubins', 'Male', 'Human', 'Hotel Rexford'),
	('Gwen McNamara', 'Female', 'Human', 'Vault 81'),
	('John Hancock', 'Male', 'Ghoul', 'Goodneighbor'),
	('Zeke', 'Male', 'Human', 'Alley Cats'), /*alley cats rule!*/
	('Solomon', 'Male', 'Human', 'Diamond City'),
	('Joe Savoldi', 'Male', 'Human', 'Bunker Hill'),
	('Duff', 'Female', 'Human', 'Diamond City'),
	('Arlen Glass', 'Male', 'Ghoul', 'The Slog'),
	('Dogmeat', 'Male', 'Dog', 'Independent'),
	('Barney Rook', 'Male', 'Human', 'Salem Volunteer Milita'),
	('Fred Allen', 'Male', 'Human', 'Goodneighbor'),
	('Geneva', 'Female', 'Human', 'Diamond City'),
	('Ness', 'Female', 'Human', 'Independent'),
	('Sheffield', 'Male', 'Human', 'Diamond City'),
	('Sheng Kawolski', 'Male', 'Human', 'Diamond City'),
	('Kessler', 'Female', 'Human', 'Bunker Hill'),
	('Whitechapel Charlie', 'Male', 'Mister Handy', 'Goodneighbor'),
	('Deb', 'Female', 'Human', 'Bunker Hill'),
	('Austin Engill', 'Male', 'Human', 'Vault 81'),
	('Thomas', 'Male', 'Human', 'Pillars of the Community'),
	('Bill Sutton', 'Male', 'Human', 'Warwick Homestead'),
	('Riley', 'Male', 'Human', 'Diamond City'),
	('Kyle', 'Male', 'Human', 'Diamond City'),
	('Vault-Tec Rep', 'Male', 'Ghoul', 'Independent'),
	('Holly', 'Female', 'Ghoul', 'The Slog'),
	('Lucy Abernathy', 'Female', 'Human', 'Abernathy Farm'),
	('Calvin Whitaker', 'Male', 'Human', 'Vault 81'),
	('Supervisor Brown', 'Male', 'Mister Handy', 'Graygarden'),
	('Supervisor Greene', 'Male', 'Mister Handy', 'Graygarden'),
	('Miss Edna', 'Female', 'Miss Nanny', 'Diamond City'),
	('Zwicky', 'Male', 'Human', 'Diamond City'),
	('Cait', 'Female', 'Human', 'Indpendent'),
	('Curie', 'Female', 'Human', 'Vault 81'),
	('Ada', 'Female', 'Robot', 'Independent'),
	('The Mechanist','Female', 'Human', 'Independent'),
	('Captain Avery', 'Female', 'Synth', 'Harbormen'),
	('Old Longfellow', 'Male', 'Human', 'Harbormen'),
	('Kasumi Nakano', 'Female', 'Human', 'Acadia'),
	('Pearl', 'Female', 'Miss Nanny', 'Vault 118'),
	('Maxwell', 'Male', 'Mister Handy', 'Vault 118'),
	('Farady', 'Male', 'Synth', 'Acadia'),
	('Chase', 'Male', 'Synth', 'Acadia'),
	('Cog', 'Male', 'Synth', 'Acadia'),
	('Dejen', 'Male', 'Synth', 'Acadia'),
	('Mai', 'Female', 'Human', 'Church of the Children of Atom'),
	('Brian Richter', 'Male', 'Human', 'Church of the Children of Atom'),
	('High Confessor Tektus', 'Male', 'Human', 'Church of the Children of Atom'),
	('Zealot Ware', 'Male', 'Human', 'Church of the Children of Atom'),
	('Cassie Dalton', 'Male', 'Human', 'Harbormen'),
	('The Mariner', 'Female', 'Human', 'Harbormen'),
	('Teddy Wright', 'Male', 'Human', 'Harbormen'),
	('Mitch', 'Male', 'Human', 'Harbormen'),
	('Small Bertha', 'Female', 'Human', 'Harbormen'),
	('William Moseley', 'Male', 'Human', 'The Institute'),
	('Valery Barstow', 'Female', 'Ghoul', 'Vault 88'),
	('RedEye', 'Male', 'Human', 'Raider Radio'),
	('Porter Gage', 'Male', 'Human', 'Nuka-World'),
	('Oswald the Outrageous', 'Male', 'Ghoul', 'Independent'),
	('Cito', 'Male', 'Human', 'Independent'),
	('Shank', 'Male', 'Human', 'Nuka-World'),
	('Fritsch', 'Male', 'Human', 'Nuka-World'),
	('Sierra Petrovita', 'Female', 'Human', 'Independent'),
	('Mackenzie Bridgeman', 'Female', 'Human', 'Nuka-World'),
	('N.I.R.A.', 'Female', 'Protectron', 'Nuka-World'),
	('Dara Hubbell', 'Female', 'Human', 'Hubologists'),
	('Mason', 'Male', 'Human', 'The Pack'),
	('Nisha', 'Female', 'Human', 'The Disciples'),
	('Mags Black', 'Female', 'Human', 'The Operators')
	