/* Rewards given out after completing a quest plus the FK that references the reward type */

INSERT INTO QuestReward(quest_reward_name, quest_reward_type_ID) VALUES
('Vault 111 Jumpsuit', 1),
	('XP', 2),
	('Pip-Boy 3000 Mark IV', 3),
	('New Companion - Codsworth', 4),
	('Bottlecaps', 5),
	('Worn Fedora', 6),
	('Faded Trench Coat', 11),
	('New Companion - Nick Valentine', 4),
	('Kellogs Pistol', 7),
	('Kellogs Outfit', 1),
	('Fusion Cells', 3),
	('Power Armor', 1),
	('New Companion - Preston Garvey', 4),
	('Flare Gun', 3),
	('The Castle', 8),
	('Artillery Schematic', 3),
	('Artillery Smoke Grenade', 7),
	('Abernathy Farm', 8),
	('Finch Farm', 8),
	('Shishkebab', 7),
	('Graygarden', 8),
	('Revelations on the Players Future', 2),
	('LocationName', 8),
	('Reightous Authority', 7),
	('Brotherhood of Steel Flag', 3),
	('Brotherhood of Steel Membership', 9),
	('Rank of Knight', 9),
	('BoS II T-60b Power Armor', 1),
	('New Companion - Paladin Danse', 4),
	('Boston Airport', 4),
	('Vertibird Signal Grenade',7),
	('T-60 Medic Pump', 3),
	('Rank of Paladin', 9),
	('BoS V T-60d Power Armor', 1),
	('T-60 Jetpack', 3),
	('Rank of Sentinel', 9),
	('Visionarys T-60c Helmet', 1),
	('T-60c Legendary Torso Piece', 1),
	('BOS Combat Armor - Chest', 1),
	('Survivors Special',7),
	('X-111 Compound', 3),
	('Membership in the Railroad', 9),
	('Deliverer Gun', 7),
	('New Companion - Deacon', 4),
	('Railway Rifle', 7),
	('Railway Spikes', 12),
	('Ticonderoga', 10),
	('Railroad Stealth Boys', 3),
	('Random Armor', 1),
	('Random Weapon', 7),
	('Institute Killer Weave', 3),
	('Stimpack', 3),
	('Ballistic Weave', 3),
	('Quarters in the Institute', 10),
	('New Comppanion - X6-88', 4),
	('Institute Paint Mod',3),
	('Fathers Lab Coat', 11),
	('Jet', 3),
	('Radaway', 3),
	('Mentats', 3),
	('Warwick Homestead', 8),
	('Liams Glasses', 11),
	('Pre-War Money', 3),
	('Plasma Grenade', 7),
	('Piezonucleic Power Armor', 3),
	('New Companion - Strong', 4),
	('Reginalds Suit', 11),
	('Agathas Dress',11),
	('Kickball', 3),
	('Teddy Bear', 3),
	('Silver Locket', 3),
	('Homing Beacons', 3),
	('Zaos Sword', 7),
	('Syringer Rifle', 7),
	('Vault 81 Room', 10),
	('New Companion - Curie', 4),
	('Covenant', 8),
	('Broadsider', 7),
	('Lieutenants Hat',11),
	('Pickmans Blade', 7),
	('Pickmans Thank You Note', 3),
	('Grognak the Barbarian', 3),
	('New Companion - Piper', 4),
	('Ashmaker', 7),
	('New Companion - John Hancock', 4),
	('Wellinghams Recipe', 3),
	('Deathclaw Guantlet', 7),
	('Shem Drowne Sword', 7),
	('Lorenzos Artifact', 6),
	('Mysterious Serum', 3),
	('Silver Shroud Gear', 1),
	('Access to Vault 81', 9),
	('Zekes Jacket',11),
	('Zekes Jeans',11),
	('Buffout', 3),
	('Jet', 3),
	('Psycho', 3), 
	('New Companion - Cait', 4),
	('Grandpa Savoldis Sword', 7),
	('2076 World Series Baseball Bat', 7),
	('New Companion - Dogmeat', 4),
	('Reba II', 7),
	('Home Plate', 8),
	('New Companion - Robert Joseph MacCready', 4),
	('Levelled Loot Cache', 13),
	('Robot Workbench Schematics', 8),
	('Mechanists Armor', 1),
	('Mechanists Helmet', 6),
	('Access To Far Harbor', 9),
	('Longfellows Cabin', 8),
	('Access To Acadia', 9),
	('Access To The Nucleus', 9),
	('Member Of The Church Of The Children Of Atom', 9),
	('Location of Vault 88', 9),
	('Vault 88',9),
	('Access To Nuka-World', 9),
	('Overboss Power Armor', 1),
	('Title Of Overboss Of Nuka-World', 9),
	('New Companion - Porter Gage', 4),
	('The Problem Solver', 7),
	('Control Of The Nuka-Cola Bottling Plant', 9),
	('Wasteland Warlord Perk Rank 2', 2),
	('Electricity To Nuka-World', 9),
	('Aeternus', 7)

