INSERT INTO LocationWorldspace (worldspace_name, region_name) VALUES
	('The Commonwealth', 'Commonwealth Wasteland'),
	('The Commonwealth', 'Concord'),
	('The Commonwealth', 'Fort Hagen Base Site'),
	('The Commonwealth', 'Lake Cochituate'),
	('The Commonwealth', 'Lexington'),
	('The Commonwealth', 'Malden Township'),
	('The Commonwealth', 'Nahant'),
	('The Commonwealth', 'Parsons'),
	('The Commonwealth', 'Quincy'),
	('The Commonwealth', 'Revere'),
	('The Commonwealth', 'Salem'),
	('The Commonwealth', 'West Roxbury'),
	('The Commonwealth', 'Cambridge'),
	('The Commonwealth', 'The Glowing Sea'),
	('Boston', 'Boston Harbor'),
	('Boston', 'Central Boston'),
	('Boston', 'East Boston'),
	('Boston', 'North Boston'),
	('Boston', 'South Boston'),
	('Boston', 'West Boston'), 
	('Far Harbor', 'Mount Desert Island'),
	('Far Harbor', 'Cranberry Island'),
	('Far Harbor', 'Acadia National Park'),
	('Far Harbor', 'The Nucleus'),
	('Nuka-World', 'Nuka-World Outskirts'),
	('Nuka-World', 'Galactic Zone'),
	('Nuka-World', 'Dry Rock Gulch'),
	('Nuka-World,', 'Safari Adventure'),
	('Nuka-World', 'Nuka-Cola Bottling Plant'),
	('Nuka-World', 'Kiddie Kingdom'),
	('Nuka-World', 'Nuka-Town USA')

